# Site settings
title: Project Euler
email: a.boulay56@gmail.com
baseurl: "/projecteuler" # the subpath of your site, e.g. /blog/
url: "http://straktor.github.io/projecteuler" # the base hostname & protocol for your site
github_username: Straktor

# Build settings
markdown: kramdown
